FROM redis:7

# Optional: Provide a custom redis config file
# COPY ./redis.conf /usr/local/etc/redis/redis.conf

# Default command (can be overridden in docker-compose)
CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
